site_name: I Segreti della Scrittura
site_description: Laboratorio di analisi multidisciplinare dedicato a codici, strutture e simbologie nascoste nei testi antichi.
theme:
  name: mkdocs
docs_dir: docs
site_dir: site

extra_css:
  - css/matrix.css

extra_javascript:
  - js/matrix.js

nav:
  - Home: index.md
  - Apocalisse (Livello Profondo): apocalisse.md
  - Le Radici in Daniele: daniele.md
  - I 5 Segreti di Isaia: isaia.md